#!/bin/bash -eu
DEV_SIDE_BINARY=$(dirname $0)/_build/default/dev.exe
# DEV_SIDE_BINARY=/path/to/_build/default/dev.native
if [ ! -f $DEV_SIDE_BINARY ]; then
  echo "$DEV_SIDE_BINARY not found (try running 'make')"
  exit 1
fi
exec qrexec-client-vm dom0 talex5.TestMirage $DEV_SIDE_BINARY "$@"
